name: WF1

on:
  release:
    types:
      - prereleased
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'Hello, World!'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo 'message'
          echo '${{ inputs.message }}'
          echo 'github.event.workflow_run.head_branch'
          echo '${{ github.event.workflow_run.head_branch }}'
          echo 'github.action'
          echo '${{ github.action }}'
          echo 'github.action_path'
          echo '${{ github.action_path }}'
          echo 'github.action_ref'
          echo '${{ github.action_ref }}'
          echo 'github.action_repository'
          echo '${{ github.action_repository }}'
          echo 'github.action_status'
          echo '${{ github.action_status }}'
          echo 'github.actor'
          echo '${{ github.actor }}'
          echo 'github.actor_id'
          echo '${{ github.actor_id }}'
          echo 'github.api_url'
          echo '${{ github.api_url }}'
          echo 'github.base_ref'
          echo '${{ github.base_ref }}'
          echo 'github.env'
          echo '${{ github.env }}'
          echo 'github.event'
          echo '${{ github.event }}'
          echo 'github.event_name'
          echo '${{ github.event_name }}'
          echo 'github.graphql_url'
          echo '${{ github.graphql_url }}'
          echo 'github.head_ref'
          echo '${{ github.head_ref }}'
          echo 'github.job'
          echo '${{ github.job }}'
          echo 'github.path'
          echo '${{ github.path }}'
          echo 'github.ref'
          echo '${{ github.ref }}'
          echo 'github.ref_name'
          echo '${{ github.ref_name }}'
          echo 'github.ref_protected'
          echo '${{ github.ref_protected }}'
          echo 'github.ref_type'
          echo '${{ github.ref_type }}'
          echo 'github.repository'
          echo '${{ github.repository }}'
          echo 'github.repository_id'
          echo '${{ github.repository_id }}'
          echo 'github.repository_owner'
          echo '${{ github.repository_owner }}'
          echo 'github.repository_owner_id'
          echo '${{ github.repository_owner_id }}'
          echo 'github.repositoryUrl'
          echo '${{ github.repositoryUrl }}'
          echo 'github.retention_days'
          echo '${{ github.retention_days }}'
          echo 'github.run_id'
          echo '${{ github.run_id }}'
          echo 'github.run_number'
          echo '${{ github.run_number }}'
          echo 'github.run_attempt'
          echo '${{ github.run_attempt }}'
          echo 'github.secret_source'
          echo '${{ github.secret_source }}'
          echo 'github.server_url'
          echo '${{ github.server_url }}'
          echo 'github.sha'
          echo '${{ github.sha }}'
          echo 'github.token'
          echo '${{ github.token }}'
          echo 'github.triggering_actor'
          echo '${{ github.triggering_actor }}'
          echo 'github.workflow'
          echo '${{ github.workflow }}'
          echo 'github.workflow_ref'
          echo '${{ github.workflow_ref }}'
          echo 'github.workflow_sha'
          echo '${{ github.workflow_sha }}'
          echo 'github.workspace'
          echo '${{ github.workspace }}'
  