name: WF2

on:
  release:
    types:
      - prereleased
  workflow_run:
    workflows:
      - WF1
    types:
      - completed
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'Hello, World!'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo '--- message  ---'
          echo '${{ inputs.message }}'
  